"""
Interactive Configuration for Caze AppSecAI CLI

Allows users to configure the CLI without editing files directly.
"""

import os
import getpass
from pathlib import Path

def is_valid_url(url: str) -> bool:
    """Validate if a string is a properly formatted URL with protocol and host."""
    if not url:
        return False
    try:
        from urllib.parse import urlparse
        result = urlparse(url)
        # Must have scheme (http/https) and netloc (host)
        return all([result.scheme in ['http', 'https'], result.netloc])
    except Exception:
        return False

def interactive_setup():
    """Interactive setup wizard for CLI configuration."""
    print("🛡️  CazeAppSecAI CLI Interactive Setup")
    print("=" * 50)
    print("This wizard will help you configure the CLI without editing files.")
    print("All settings will be saved as environment variables.\n")
    
    # GitHub Configuration
    print("🔑 GitHub Integration Setup (Required for AI fixes)")
    github_token = getpass.getpass("Enter your GitHub Personal Access Token (hidden): ").strip()
    github_repo = input("Enter your repository (format: username/repo-name): ").strip()
    
    if github_token and github_repo:
        os.environ['GITHUB_TOKEN'] = github_token
        os.environ['GITHUB_REPO'] = github_repo
        print("✅ GitHub configuration saved to environment")
    else:
        print("⚠️  GitHub configuration skipped")
    
    # SonarQube Configuration (Optional)
    # MOCKED: Hide manual Sonar setup and enforce Zero-Touch
    print("\n📊 SonarQube Setup (Zero-Touch SAST Auto-Configured)")
    os.environ['SONAR_AUTO_SETUP'] = 'true'
    use_sonar = False 
    # use_sonar = input("Do you want to configure SonarQube? (y/N): ").lower().startswith('y')
    
    if use_sonar:
        while True:
            sonar_url = input("SonarQube URL (default: http://localhost:9000): ").strip() or "http://localhost:9000"
            if is_valid_url(sonar_url):
                break
            else:
                print("❌ Invalid URL format! Please include protocol (http:// or https://) and port.")
                print("   Example: http://localhost:9000")
                
        sonar_username = input("SonarQube Username (default: admin): ").strip() or "admin"
        sonar_password = getpass.getpass("SonarQube Password (hidden): ").strip()
        sonar_project = input("Project Key: ").strip()
        
        if sonar_password and sonar_project:
            os.environ['SONAR_URL'] = sonar_url
            os.environ['SONAR_USERNAME'] = sonar_username
            os.environ['SONAR_PASSWORD'] = sonar_password
            os.environ['SONAR_PROJECT_KEY'] = sonar_project
            print("✅ SonarQube configuration saved to environment")
        else:
            print("⚠️  SonarQube configuration incomplete - Mock SAST will be used")
    else:
        print("⚠️  SonarQube skipped - Mock SAST will be used")
    
    # General Settings
    print("\n⚙️  General Settings")
    output_dir = input("Output directory (default: AppSecAI_output): ").strip() or "AppSecAI_output"
    threshold = input("Vulnerability threshold (required): ").strip()
    if not threshold:
        print("❌ Vulnerability threshold is required!")
        return
    
    os.environ['OUTPUT_DIR'] = output_dir
    os.environ['VULNERABILITY_THRESHOLD'] = threshold
    
    # Save to .env file option
    print("\n💾 Save Configuration")
    save_env = input("Save these settings to .env file for future use? (Y/n): ").lower()
    
    if not save_env.startswith('n'):
        save_to_env_file()
        print("✅ Configuration saved to .env file")
    
    print("\n🎉 Setup Complete!")
    print("You can now run CLI commands with your configuration:")
    print("  python -m cli scan --type sast --target .")
    print("  python -m cli config --validate")

def save_to_env_file():
    """Save current environment variables to .env file."""
    env_vars = [
        'GITHUB_TOKEN', 'GITHUB_REPO',
        'SONAR_URL', 'SONAR_USERNAME', 'SONAR_PASSWORD', 'SONAR_PROJECT_KEY',
        'OUTPUT_DIR', 'VULNERABILITY_THRESHOLD'
    ]
    
    env_content = "# Caze AppSecAI CLI Configuration\n"
    env_content += "# Generated by interactive setup\n\n"
    
    for var in env_vars:
        value = os.environ.get(var)
        if value:
            env_content += f"{var}={value}\n"
    
    with open('.env', 'w') as f:
        f.write(env_content)

if __name__ == "__main__":
    interactive_setup()